#ifndef _DEBUG_VERSION_H
#define _DEBUG_VERSION_H
//#define INTERNAL_VERSION_TESTING  // IMPORTANT **** NEED TO REMOVE THIS FLAG IF WANNA RELEASE FOR MASS
// NOTICE THESE APPS NEED TO BE RECOMPILED AFTER CHANGING THE FLAG ABOVE

//1. BMMANAGER
//2. MJPG_STREAMER
#endif
